before:
  hooks:
    - make clean

builds:
  - binary: s3parcp
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
    ldflags:
      - "-w -s -X github.com/chanzuckerberg/s3parcp/util.GitSha={{.Commit}} -X github.com/chanzuckerberg/s3parcp/util.Version={{.Version}} -X github.com/chanzuckerberg/s3parcp/util.Dirty=false -X github.com/chanzuckerberg/s3parcp/util.Release=true"

archives:
  - files:
    - none*

release:
  prerelease: true

env_files:
  github_token: ~/.config/goreleaser/github_token