before:
  hooks:
    - go mod tidy

builds:
- env:
  - CGO_ENABLED=0
  goos:
    - darwin
    - linux
  goarch:
    - amd64

release:
  prerelease: {{ .Env.PRERELEASE }}

archives:
  - files:
    - LICENSE
    - README.md
    - completions/**/*

brews:
- description: "Copy large files to, from, and between s3 buckets with parallelism"
  tap:
    owner: chanzuckerberg
    name: homebrew-tap
    token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
  homepage: "https://github.com/chanzuckerberg/s3parcp"
  test: system "#{bin}/s3parcp --version"
  install: |
    bin.install "s3parcp"
    bash_completion.install "completions/bash" => "s3parcp"
    zsh_completion.install "completions/zsh" => "_s3parcp"

nfpms:
  - 
    vendor: chanzuckerberg
    maintainer: Todd Morse <todd@morsecodist.io>
    homepage: "https://github.com/chanzuckerberg/s3parcp"
    description: "Copy large files to, from, and between s3 buckets with parallelism"
    license: MIT
    formats:
      - deb
      - rpm
    files:
      "completions/bash": "/etc/bash_completion.d/s3parcp"
      "completions/zsh": "/usr/share/zsh/functions/Completion/_s3parcp"

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
    - "^docs:"
    - "^test:"
