before:
  hooks:
    - make clean
    - make packr

builds:
  - binary: s3parcp
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
    ldflags:
      - "-w -s -X github.com/chanzuckerberg/s3parcp/util.GitSha={{.Commit}} -X github.com/chanzuckerberg/s3parcp/util.Version={{.Version}} -X github.com/chanzuckerberg/s3parcp/util.Dirty=false -X github.com/chanzuckerberg/s3parcp/util.Release=true"

archives:
  - files:
    - none*

release:
  prerelease: true

# image_template uses .ShortCommit for a unique tag that fits semver's guidelines and docker tagging requirements
# We use .Version for .goreleaser.yml
dockers:
  - dockerfile: Dockerfile
    image_templates:
      - docker.pkg.github.com/chanzuckerberg/s3parcp/s3parcp:{{.ShortCommit}}
    extra_files:
      - cmd
      - go.mod
      - go.sum
      - main.go
      - vendor
      - apply
      - config
      - docs
      - errs
      - exp
      - init
      - migrations
      - plan
      - plugins
      - setup
      - templates
      - util

env_files:
  github_token: ~/.config/goreleaser/github_token