dist: bionic
language: go
go:
  - "1.13.1"
install:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh
jobs:
  include:
    - name: lint
      stage: check
      script: ./bin/golangci-lint run

    - name: vet
      stage: check
      script: go vet ./...

    - name: format
      stage: check
      script: test -z $(gofmt -l .)

    - name: test
      stage: check
      script: go test ./...

    - name: deploy
      stage: deploy
      script: curl -sL https://git.io/goreleaser | bash
      if: tag =~ /^v 
