dist: bionic
language: go
go:
  - "1.13.1"
install:
  - scripts/download-golangci-lint.sh
env:
  - GO111MODULE=on
jobs:
  include:
    - name: lint
      stage: check
      script: ./bin/golangci-lint run

    - name: format
      stage: check
      script: test -z $(gofmt -l .)

    - name: test
      stage: check
      script: go test ./...

    - name: deploy
      stage: deploy
      script: scripts/deploy.sh
      if: tag =~ /^v 
