dist: bionic
language: go
go:
  - "1.13.1"
install:
  - make setup
jobs:
  include:
    - name: lint
      stage: check
      script:
        - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh
        - ./bin/golangci-lint run

    - name: test
      stage: check
      script: go test -cover ./...
      after_success:
        - bash <(curl -s https://codecov.io/bash)
