name: Go

on:
  push:
  pull_request:

jobs:

  Go:
    name: Go
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        make setup

    - name: Build
      run: make build

    - name: Test
      run: |
        make test-coverage
        bash <(curl -s https://codecov.io/bash)

    - name: Lint
      run: make lint

    - name: Deps
      run: |
        make deps
        git diff --exit-code

    - name: Release
      uses: goreleaser/goreleaser-action@v2
      if: startsWith(github.ref, 'refs/tags/v')
      with:
        version: latest
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
